apiVersion: v1
kind: ConfigMap
metadata:
  name: test-execution-config
  namespace: test-execution
data:
  DB_HOST: "test-execution-postgres"
  DB_PORT: "5432"
  DB_NAME: "test_execution_db"
  DB_USER: "postgres"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8000"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  WORKSPACE_DIR: "/tmp/test_workspaces"
  LOG_DIR: "/tmp/test_logs"
  REPORTS_DIR: "/tmp/test_reports"
  MAX_CONCURRENT_EXECUTIONS: "5"
  EXECUTION_TIMEOUT: "3600"
---
apiVersion: v1
kind: Secret
metadata:
  name: test-execution-secrets
  namespace: test-execution
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded values
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  GITHUB_TOKEN: eW91cl9naXRodWJfdG9rZW5faGVyZQ==  # your_github_token_here
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWhlcmU=  # your-secret-key-here 